name: Deploy Frontend
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to DockerHub
      env:
          DOCKER_USERNAME: sudayanga  # Replace with your DockerHub username
      run: docker login -u $DOCKER_USERNAME --password ${{ secrets.DOCKER_TOKEN }}
   
    - run: docker build -t cygnetops/react-test -f Dockerfile.dev .
    - run: docker run -e CI=true cygnetops/react-test npm test
 
    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v18
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: $APP_NAME
        environment_name: Docker-react-app-env
        existing_bucket_name: elasticbeanstalk-$AWS_REGION-854544130908
        region: $AWS_REGION
        version_label: ${{ github.sha }}
        deployment_package: deploy.zip
